[package]
name = "tokio-socks"
description = "Asynchronous SOCKS proxy support for Rust."
documentation = "https://docs.rs/tokio-socks"
homepage = "https://github.com/sticnarf/tokio-socks"
repository = "https://github.com/sticnarf/tokio-socks"
readme = "README.md"
categories = ["asynchronous", "network-programming"]
keywords = ["tokio", "async", "proxy", "socks", "socks5"]
license = "MIT"
version = "0.2.0"
authors = ["Yilin Chen <sticnarf@gmail.com>"]
edition = "2018"

[badges]
travis-ci = { repository = "sticnarf/tokio-socks" }

[features]
tor = []

[[example]]
name="tor"
required-features=["tor"]

[dependencies]
futures = "0.3"
tokio = { version="0.2", default-features = false, features = ["io-util", "stream", "tcp"] }
bytes = "0.4"
failure = "0.1"
derefable = "0.1"
either = "1"

[dev-dependencies]
tokio = { version = "0.2", features = ["io-util"] }
once_cell = "1.2.0"
hyper = "0.13"
